# 注意：如果clash或sing-box使用mosdns，必须将DNS部分指向mosdns的监听地址和端口，请参考博客有关设置的说明
log:
  level: info
  file: "/var/log/mosdns.log"

include: []

plugins:
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/usr/local/etc/mosdns/rule/geosite_cn.txt"

  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/usr/local/etc/mosdns/rule/geoip_cn.txt"

  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/usr/local/etc/mosdns/rule/geosite_geolocation-!cn.txt"

  - tag: whitelist
    type: domain_set
    args:
      files:
        - "/usr/local/etc/mosdns/rule/whitelist.txt"

  - tag: blocklist
    type: domain_set
    args:
      files:
        - "/usr/local/etc/mosdns/rule/blocklist.txt"

  - tag: greylist
    type: domain_set
    args:
      files:
        - "/usr/local/etc/mosdns/rule/greylist.txt"

  - tag: ddnslist
    type: domain_set
    args:
      files:
        - "/usr/local/etc/mosdns/rule/ddnslist.txt"

  - tag: hosts
    type: hosts
    args:
      files:
        - "/usr/local/etc/mosdns/rule/hosts.txt"

  - tag: redirect
    type: redirect
    args:
      files:
        - "/usr/local/etc/mosdns/rule/redirect.txt"

  - tag: adlist
    type: domain_set
    args:
      files:
        - "/usr/local/etc/mosdns/rule/adlist.txt"

  - tag: local_ptr
    type: domain_set
    args:
      files:
        - "/usr/local/etc/mosdns/rule/local-ptr.txt"

  - tag: lazy_cache
    type: cache
    args:
      size: 0
      lazy_cache_ttl: 0
      dump_file: /etc/mosdns/cache.dump
      dump_interval: 0

  - tag: reject_3
    type: sequence
    args:
      - exec: reject 3

  - tag: reject_blocklist
    type: sequence
    args:
      - exec: query_summary reject_blocklist
      - exec: $reject_3

  - tag: reject_adlist
    type: sequence
    args:
      - exec: query_summary reject_adlist
      - exec: $reject_3

  - tag: reject_ptrlist
    type: sequence
    args:
      - exec: query_summary reject_ptrlist
      - exec: $reject_3

  - tag: reject_qtype65
    type: sequence
    args:
      - exec: query_summary reject_qtype65
      - exec: $reject_3

  - tag: forward_local
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "223.5.5.5"
          enable_http3: true
        - addr: "quic://223.5.5.5"

  - tag: forward_remote
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: udp://127.0.0.1:1053 #sing-box、clash或unbound dns监听地址
        - addr: tcp://127.0.0.1:1053 #sing-box 、clash 或unbound dns监听地址
          enable_pipeline: false
          insecure_skip_verify: false
          idle_timeout: 50
          enable_http3: false

  - tag: forward_google
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8"
          socks5: "127.0.0.1:7891" ##sing-box 或clash socks地址

  - tag: forward_cf
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "https://dns.cloudflare.com/dns-query"
          dial_addr: "1.1.1.1"
          socks5: "127.0.0.1:7891" ##sing-box或clash socks地址

  - tag: modify_ttl
    type: sequence
    args:
      - exec: ttl 0-0

  - tag: modify_ddns_ttl
    type: sequence
    args:
      - exec: ttl 5-5

  - tag: local_sequence
    type: sequence
    args:
      - exec: query_summary forward_local
      - exec: $forward_local

  - tag: remote_sequence
    type: sequence
    args:
      - exec: query_summary forward_remote
      - exec: $forward_remote

  - tag: forward_google_upstream
    type: sequence
    args:
      - exec: query_summary forward_google
      - exec: $forward_google

  - tag: forward_cf_upstream
    type: sequence
    args:
      - exec: query_summary forward_cf
      - exec: $forward_cf

  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: qname $ddnslist
        exec: $modify_ddns_ttl
      - matches: "!qname $ddnslist"
        exec: $modify_ttl
      - matches: has_resp
        exec: accept

  - tag: query_is_ddns_domain
    type: sequence
    args:
      - matches: qname $ddnslist
        exec: $local_sequence

  - tag: query_is_srv_domain
    type: sequence
    args:
      - matches:
          - qtype 33
        exec: $forward_google_upstream

  - tag: query_is_mx_domain
    type: sequence
    args:
      - matches:
          - qtype 15
        exec: $forward_google_upstream

  - tag: query_is_local_domain
    type: sequence
    args:
      - matches: qname $geosite_cn
        exec: $local_sequence

  - tag: query_is_no_local_domain
    type: sequence
    args:
      - matches: qname $geosite_no_cn
        exec: $remote_sequence

  - tag: query_is_whitelist_domain
    type: sequence
    args:
      - matches: qname $whitelist
        exec: $local_sequence

  - tag: query_is_greylist_domain
    type: sequence
    args:
      - matches: qname $greylist
        exec: $remote_sequence

  - tag: query_is_reject_domain
    type: sequence
    args:
      - matches: qname $blocklist
        exec: $reject_blocklist
      - matches: qname $adlist
        exec: $reject_adlist
      - matches:
          - qtype 12
          - qname $local_ptr
        exec: $reject_ptrlist
      - matches: qtype 65
        exec: $reject_qtype65

  - tag: fallback_sequence
    type: sequence
    args:
      - exec: $forward_google_upstream
      - matches: "rcode 2"
        exec: goto local_sequence
      - matches: "rcode 3"
        exec: goto forward_cf_upstream
      - matches: "rcode 5"
        exec: goto local_sequence
      - matches: "resp_ip $geoip_cn"
        exec: goto local_sequence
      - matches: "!resp_ip 0.0.0.0/0 ::/0"
        exec: accept
      - matches: "!resp_ip $geoip_cn"
        exec: goto remote_sequence

  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - exec: jump has_resp_sequence
      - matches:
          - "!qname $ddnslist"
          - "!qname $blocklist"
          - "!qname $adlist"
          - "!qname $local_ptr"
        exec: $lazy_cache
      - exec: $redirect
      - exec: jump has_resp_sequence
      - exec: $query_is_ddns_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_srv_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_mx_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_reject_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_whitelist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_greylist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_local_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_no_local_domain
      - exec: jump has_resp_sequence
      - exec: $fallback_sequence

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":2053" #mosdns的监听端口

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":2053" #mosdns的监听端口
