log:
  level: warn
  production: true
  file: "/var/log/mosdns.log"

plugins:
  - tag: "cache"
    type: cache
    args:
      size: 32768
      lazy_cache_ttl: 86400
      dump_file: "/var/db/mosdns.cache"
      dump_interval: 300

  - tag: "reverse_lookup"
    type: reverse_lookup
    args:
      size: 5000
      ttl: 14400
      handle_ptr: true

  - tag: "remote_domain_set"
    type: domain_set
    args:
      files:
        - "./domains/gfw.txt"
        - "./domains/proxy-list.txt"

  - tag: "direct_domain_set"
    type: domain_set
    args:
      files:
        - "./domains/direct-list.txt"

  - tag: "direct_ip"
    type: ip_set
    args:
      files:
        - "./ips/all_cn.txt"

  - tag: "remote_forward"
    type: forward
    args:
      upstreams:
        - tag: cloudflare_doh
          addr: "https://cloudflare-dns.com/dns-query"
          enable_pipeline: true
          idle_timeout: 10

        - tag: google_doh
          addr: "https://dns.google/dns-query"
          enable_pipeline: true
          idle_timeout: 10      

        - tag: quad9_doh
          addr: "https://dns.quad9.net/dns-query"
          enable_pipeline: true
          idle_timeout: 10

        - tag: opendns_doh
          addr: "https://doh.opendns.com/dns-query"
          enable_pipeline: true
          idle_timeout: 10

        - tag: google_dot
          addr: "tls://8.8.8.8:853"
          enable_pipeline: true
          idle_timeout: 10

  - tag: "domestic_forward"
    type: forward
    args:
      upstreams:
        - tag: ali_doh
          addr: "https://dns.alidns.com/dns-query"
          enable_pipeline: true
          idle_timeout: 10

        - tag: dnspod_doh
          addr: "https://doh.pub/dns-query"
          enable_pipeline: true
          idle_timeout: 10

        - tag: 360_doh
          addr: "https://doh.360.cn/dns-query"
          enable_pipeline: true
          idle_timeout: 10

        - tag: ali_udp
          addr: "udp://223.5.5.5"
          enable_pipeline: true

  - tag: "ttl_sequence"
    type: sequence
    args:
      - exec: ttl 600-86400
      - exec: accept

  - tag: "domestic_sequence"
    type: sequence
    args:
      - exec: $domestic_forward
      - exec: goto ttl_sequence

  - tag: "remote_sequence"
    type: sequence
    args:
      - exec: $remote_forward
      - matches: "resp_ip $direct_ip"
        exec: $domestic_forward
      - exec: goto ttl_sequence

  - tag: "fallback"
    type: fallback
    args:
      primary: domestic_sequence
      secondary: remote_sequence
      threshold: 800
      always_standby: true

  - tag: "main_sequence"
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $cache
      - matches: has_resp
        exec: accept
      - exec: $reverse_lookup
      - matches: has_resp
        exec: accept
      - matches: "qname $remote_domain_set"
        exec: goto remote_sequence
      - matches: "qname $direct_domain_set"
        exec: goto domestic_sequence
      - exec: $fallback

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :5335